-- VHDL Entity controller_IT_lib.interface.interface
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-06)
--          at - 17:23:44 30/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.Numeric_Std.all;
LIBRARY controller_IT_lib;
USE controller_IT_lib.controller_IT_package.all;

ENTITY interface IS
   PORT( 
      EN            : IN     Def_EN;
      RnW           : IN     Def_bit;
      addr          : IN     Def_addr;
      blx           : IN     Def_addr;
      clk           : IN     Def_bit;
      masque        : IN     Def_masque;
      nAS           : IN     Def_bit;
      nCS_IT        : IN     Def_bit;
      nRST          : IN     Def_bit;
      pending       : IN     Def_pending;
      vect_handler  : IN     Def_vect_handler;
      vect_priorite : IN     Def_vect_priorite;
      d_bus         : OUT    Def_data
   );

-- Declarations

END interface ;

--
-- VHDL Architecture controller_IT_lib.interface.RTL
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-06)
--          at - 17:23:44 30/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.Numeric_Std.all;

LIBRARY controller_IT_lib;
USE controller_IT_lib.controller_IT_package.ALL;


ARCHITECTURE RTL OF interface IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT interface_read
   PORT (
      d_bus         : OUT    Def_data ;
      clk           : IN     Def_bit ;
      nAS           : IN     Def_bit ;
      nCS_IT        : IN     Def_bit ;
      nRST          : IN     Def_bit ;
      RnW           : IN     Def_bit ;
      EN            : IN     Def_EN ;
      vect_priorite : IN     Def_vect_priorite ;
      pending       : IN     Def_pending ;
      masque        : IN     Def_masque ;
      addr          : IN     Def_addr ;
      blx           : IN     Def_addr ;
      vect_handler  : IN     Def_vect_handler 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : interface_read USE ENTITY controller_IT_lib.interface_read;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : interface_read
      PORT MAP (
         d_bus         => d_bus,
         clk           => clk,
         nAS           => nAS,
         nCS_IT        => nCS_IT,
         nRST          => nRST,
         RnW           => RnW,
         EN            => EN,
         vect_priorite => vect_priorite,
         pending       => pending,
         masque        => masque,
         addr          => addr,
         blx           => blx,
         vect_handler  => vect_handler
      );

END RTL;
