-- VHDL Entity work.interface.interface
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-12)
--          at - 18:05:55 14/12/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
USE IEEE.Numeric_Std.all;
LIBRARY work;
USE work.controller_IT_package.all;

ENTITY interface IS
   PORT( 
      RnW     : IN     Def_bit;
      addr    : IN     Def_addr;
      blx     : IN     Def_addr;
      clk     : IN     Def_bit;
      nAS     : IN     Def_bit;
      nCS_IT  : IN     Def_bit;
      nRST    : IN     Def_bit;
      d_bus   : INOUT  Def_data;
      EN            : INOUT Def_EN;
      masque        : INOUT Def_masque;
      pending : IN     Def_pending;
      vect_handler  : INOUT Def_vect_handler;
      vect_priorite : INOUT Def_vect_priorite;
      ack_read : out std_logic
   );

-- Declarations

END interface ;

--
-- VHDL Architecture work.interface.RTL
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-12)
--          at - 18:06:22 14/12/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
USE IEEE.Numeric_Std.all;

LIBRARY work;
USE work.controller_IT_package.ALL;


ARCHITECTURE Arch OF interface IS

   -- Architecture declarations

   -- Internal signal declaration


   -- Component Declarations
   COMPONENT interface_read
   PORT (
      d_bus         : OUT    Def_data ;
      clk           : IN     Def_bit ;
      nAS           : IN     Def_bit ;
      nCS_IT        : IN     Def_bit ;
      nRST          : IN     Def_bit ;
      RnW           : IN     Def_bit ;
      EN            : IN     Def_EN ;
      vect_priorite : IN     Def_vect_priorite ;
      masque        : IN     Def_masque ;
      addr          : IN     Def_addr ;
      vect_handler  : IN     Def_vect_handler ;
      blx           : IN     Def_addr ;
      pending       : IN     Def_pending ;
      Ack_Read      : OUT    Def_bit
   );
   END COMPONENT;
   COMPONENT interface_write
   PORT (
      d_bus         : IN     Def_data ;
      nRST          : IN     Def_bit ;
      RnW           : IN     Def_bit ;
      EN            : OUT    Def_EN ;
      vect_priorite : OUT    Def_vect_priorite ;
      masque        : OUT    Def_masque ;
      addr          : IN     Def_addr ;
      vect_handler  : OUT    Def_vect_handler ;
      nCS_IT        : IN     Def_bit ;
      clk           : IN     Def_bit ;
      nAS           : IN     Def_bit 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : interface_read USE ENTITY work.interface_read;
   --FOR ALL : interface_write USE ENTITY work.interface_write;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : interface_read
      PORT MAP (
         d_bus         => d_bus,
         clk           => clk,
         nAS           => nAS,
         nCS_IT        => nCS_IT,
         nRST          => nRST,
         RnW           => RnW,
         EN            => EN,
         vect_priorite => vect_priorite,
         masque        => masque,
         addr          => addr,
         vect_handler  => vect_handler,
         blx           => blx,
         pending       => pending,
         Ack_Read => ack_read
      );

   U_1 : interface_write
      PORT MAP (
         d_bus         => d_bus,
         nRST          => nRST,
         RnW           => RnW,
         EN            => EN,
         vect_priorite => vect_priorite,
         masque        => masque,
         addr          => addr,
         vect_handler  => vect_handler,
         nCS_IT        => nCS_IT,
         clk           => clk,
         nAS           => nAS
      );

END Arch;
