-- VHDL Entity work.IP_IT.symbol
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-06)
--          at - 17:20:18 30/11/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_arith.all;
use IEEE.Numeric_Std.all;
--library work;
use work.controller_IT_package.all;

entity top_level_design is
  -- Declarations
  port (
    d_bus : inout Def_data;
    nAS : in Def_bit;
    nRST : in Def_bit;
    addr : out Def_addr;
    clk : in Def_bit;
    RnW : in Def_bit;
    nCS_IT : in Def_bit;
    nIT_xxx : in unsigned(IT_size - 1 downto 0)
  );
end top_level_design;

--
-- VHDL Architecture work.IP_IT.RTLt
--
-- Created:
--          by - E20B103C.UNKNOWN (irc107-06)
--          at - 15:40:13 08/12/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_arith.all;
use IEEE.Numeric_Std.all;
library work;
use work.controller_IT_package.all;
architecture Arch of top_level_design is

  -- Architecture declarations

  -- Component Declarations
  component interface
    port (
      RnW : in Def_bit;
      addr : in Def_addr;
      blx : in Def_addr;
      clk : in Def_bit;
      nAS : in Def_bit;
      nCS_IT : in Def_bit;
      nRST : in Def_bit;
      d_bus : inout Def_data;
      EN : inout Def_EN;
      masque : inout Def_masque;
      pending : in Def_pending;
      vect_handler : inout Def_vect_handler;
      vect_priorite : inout Def_vect_priorite;
      Ack_Read : out Def_bit
    );
  end component;

  component mask_entity
    port (
      nIT_xxx : in unsigned(IT_size - 1 downto 0);
      mask : in Def_masque;
      nIT_xxx_masked : out unsigned(IT_size - 1 downto 0)
    );
  end component;

  component priority_solver
    port (
      nIT_xxx : in unsigned(IT_size - 1 downto 0);
      priority_vector : in Def_vect_priorite;
      id_it : out unsigned(NB_BIT_IT - 1 downto 0);
      is_IT_active : out std_logic
    );
  end component;

  component gestion_blx is
    port (
      clk : in std_logic;
      nRST : in std_logic;
      nIT_CPU : out Def_bit;
      id_it : in unsigned(NB_BIT_IT - 1 downto 0);
      ack_read : in std_logic;
      is_IT_active : in std_logic;
      blx : out Def_addr;
      vect_handler : in Def_vect_handler
    );
  end component;

  -- Optional embedded configurations
  -- pragma synthesis_off
  -- FOR ALL : interface USE ENTITY work.interface;
  -- FOR ALL : interface_tb USE ENTITY work.interface_tb;
  -- pragma synthesis_on
  signal blx : Def_addr;
  signal pending : Def_pending;
  signal mask : Def_masque;
  signal nIT_xxx_masked : unsigned(IT_size - 1 downto 0);
  signal vect_handler : Def_vect_handler;
  signal vect_priorite : Def_vect_priorite;
  signal Ack_Read : Def_bit;
  signal is_IT_active : std_logic;
  signal id_it : unsigned(NB_BIT_IT - 1 downto 0);


begin

  -- Instance port mappings.
  U_interface : interface
  port map(
    RnW => RnW,
    addr => addr,
    clk => clk,
    nAS => nAS,
    nCS_IT => nCS_IT,
    nRST => nRST,
    d_bus => d_bus,
    pending => pending,
    blx => blx,
    masque => mask,
    vect_handler => vect_handler,
    vect_priorite => vect_priorite,
    Ack_Read => ack_read
  );

  U_mask : mask_entity
  port map(
    nIT_xxx => nIT_xxx,
    mask => mask,
    nIT_xxx_masked => nIT_xxx_masked
  );

  u_prio_solver : priority_solver
  port map(
    nIT_xxx => nIT_xxx_masked,
    priority_vector => vect_priorite,
    id_it => id_it,
    is_it_active => is_IT_active
  );

  u_gest_blx : gestion_blx
  port map(
    clk => clk,
    nRST => nRST,
    blx => blx,
    vect_handler => vect_handler,
    id_it => id_it,
    Ack_Read => ack_read,
    is_IT_active => is_IT_active
  );

end Arch;